project:
  type: website

website:
  title: "Dom6Stats"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: [flatly, dom6.scss]
    toc: true



